[TOC]

# 捕获异常

捕捉异常可以是try/except语句。try/except语句用来检测try语句块中的错误，从而让except语句捕获异常信息并处理。如果不想在异常发生时结束程序，只需在try里捕获它

## 异常的抛出机制

1. 如果在运行时发生异常，解释器会查找相应的处理语句（成为handler）
2. 要是在当前函数里没有找到的话，它会将异常传递给上层的调用函数，看看那里能不能处理
3. 如果在最外层（全局“main”）还是没有找到的话，解释器就会退出，同时打印traceback以便让用户找到错误产生的原因

==注：虽然大多数错误会导致异常，但是一个异常不一定代表错误，有时候它们只是一个警告，有时候它们可能是一个终止信号，比如退出循环==

## try...except...else

语法：

```python
try:
	<语句> #运行代码
except<name>:
	<语句> #如果在try部分引发了name异常
else:
	<语句> #如果没有异常发生
```

## try的工作原理：

当开始一个try语句后，python就在当前程序的上下文中做标记，这样当异常出现时就可以回到这里，try子句先执行，接下来会发生什么依赖于执行时是否出现异常

* 如果try后的语句执行时发生异常，python就执行第一个匹配该异常的except子句，异常处理完毕就跳出整个try语句，程序继续向下执行
* 如果当try后的语句执行时发生异常，却没有匹配的excep子句，异常将被递交到上层的try，或者到程序的最上层，这样将结束程序，并打印缺省的出错信息
* 如果在try子句执行时没有发生异常，如果由else的话，python将执行else语句，然后程序继续向下执行

![1565666345090](E:\Typora笔记\Python\assets\1565666345090.png)

![1565666459140](E:\Typora笔记\Python\assets\1565666459140.png)

## 使用except 而不带任何异常类型

使用except 时指定异常类型（如实例2异常类型为ZeroDivisionError）就只能捕获这一类型的异常。如果不指定任何异常类型，==这种方式的try-except 语句就可以捕获所有发生的异常但这不是一个很好的方式，因为无法通过该程序识别出具体的异常信息==。因为它捕获所有的异常。

![1565667684445](E:\Typora笔记\Python\assets\1565667684445.png)

![1565667702534](E:\Typora笔记\Python\assets\1565667702534.png)

## try-finally

无论是否发生异常都将执行最后的代码

![1565667802676](E:\Typora笔记\Python\assets\1565667802676.png)

![1565667819250](E:\Typora笔记\Python\assets\1565667819250.png)

# 获取异常信息

使用try-except而不带任何异常类型虽然可以捕获所有发生的异常。但是无法知道异常的具体信息

获取异常信息对于程序的调试非常重要，可以有助于快速定位有错误程序语句的位置，介绍三种python中获取异常信息的方法，这里获取异常（Exception）信息采用try..except...程序结构

![1565668008424](E:\Typora笔记\Python\assets\1565668008424.png)

使用as关键字为捕获的异常设置一个简单的别名e

1. str(e):返回字符串类型，只给出异常信息，不包括异常信息的类型，例如除数为0的异常信息：‘integer division or modulo by zero’
2. repr(e):给出较全的异常信息，包括异常信息的类型，例如除数为0的异常信息
3. 采用traceback模块：需要导入traceback模块，使用traceback.format_exc()获取的信息最全，于python命令行运行程序出现错误信息一致

![1565668283465](E:\Typora笔记\Python\assets\1565668283465.png)

# Raise触发异常

在python中可以使用raise语句自己触发异常，一旦执行了raise语句，raise后面的语句将不能执行

raise语法格式如下

```python
raise [Exception[,args[,traceback]]]
```

* Exception:是异常的类型（例如：NameError），定义的异常类型必须是python提供的，该参数是可选的，如不提供，异常的参数是“None”
* traceback：可选的（在实践中很少使用），如果存在，是跟踪异常对象

![1565668513686](E:\Typora笔记\Python\assets\1565668513686.png)

# 常见的异常类型

| 异常名称               | 描述                                                 |
| ---------------------- | ---------------------------------------------------- |
| BaseException          | 所有异常的基类                                       |
| SystemExit             | 解释器请求退出                                       |
| KeyboardInterrupt      | 用户中断执行(ctrl+C)                                 |
| Exception              | 常规错误的基类                                       |
| StopIteration          | 迭代器没有更多的值                                   |
| GeneratorExit          | 生成器（generator）发生异常来通知退出                |
| SatandardError         | 所有的内建标准异常的基类                             |
| ArithmeticError        | 所有数值计算错误的基类                               |
| FloatingPointError     | 浮点计算错误                                         |
| OverflowError          | 数值运算超出最大限制                                 |
| ZeroDivisionError      | 除（或取模）零(所有数据类型)                         |
| AssertionError         | 断言语句失败                                         |
| AttributeError         | 对象没有这个属性                                     |
| EOFError               | 没有内建输入，到达EOF标记                            |
| EnvironmentError       | 操作系统错误的基类                                   |
| IOError                | 输入/输出操作失败                                    |
| OSError                | 操作系统错误                                         |
| WindowsError           | 系统调用失败                                         |
| ImportError            | 导入模块/对象失败                                    |
| LookupError            | 无效数据查询的基类                                   |
| IndexError             | 序列中没有此索引（index）                            |
| KeyError               | 映射中没有这个键                                     |
| MemoryError            | 内存溢出错误（对于python解释器不是致命的）           |
| NameError              | 未声明/初始化对象（没有属性）                        |
| UnboundLocalError      | 访问未初始化的本地变量                               |
| ReferenceError         | 弱引用（Weak reference）试图访问已经垃圾回收了的对象 |
| RuntimeError           | 一般运行时错误                                       |
| NotImplementedError    | 没有实现的方法                                       |
| SyntaxError            | python语法错误                                       |
| IndentationError       | 缩进错误                                             |
| TabError               | Tab和空格混用                                        |
| SystemError            | 一般的解释器系统错误                                 |
| TypeError              | 对类型无效的操作                                     |
| ValueError             | 传入无效的参数                                       |
| UnicodeError           | Unicode相关的错误                                    |
| UnicodeDecodeError     | Unicode解码时的错误                                  |
| UnicodeEncodeError     | Unicode编码时的错误                                  |
| UnicodeTranslateError  | Unicode转换时的错误                                  |
| Warning                | 警告的基类                                           |
| DeprecationWarning     | 关于被弃用的特征的警告                               |
| FutureWarning          | 关于构造将来语义会有改变的警告                       |
| OverflowWarning        | 旧的关于自动提升为长整型（long）的警告               |
| pendingDeprecatWarning | 关于特性将会被废弃的警告                             |
| RuntimeWarning         | 可疑的运行时行为（runtime behavior）的警告           |
| SyntaxWarning          | 可疑的语法的警告                                     |
| UserWarning            | 用户代码生成的警告                                   |

